name: code-checker

on:
  push:

jobs:
  code-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Prepare build"
        run: |
          mkdir -pv Build
          cd Build
          make ..

      - uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          logfile: ${{ github.workspace }}/Build/compile_commands.json

      - uses: actions/upload-artifact@v2
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}